using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Xml;
using System.Xml.Linq;

namespace Void;

/// <summary>
/// Build-time converter from an authored Tiled <c>.tmx</c> map to the runtime
/// prefab JSON that <see cref="PrefabRegistryLoader"/> loads (VOID-026).
///
/// The committed <c>.tmx</c> under <c>content/tiled/</c> is the single source of
/// truth for a generated prefab; <c>data/prefabs/generated/*.json</c> is its
/// committed output, regenerated by <c>Void.Tools tmx-convert</c>. The XML is
/// parsed directly, so neither CI nor a fresh clone needs Tiled installed and
/// there is no intermediate export step to forget to re-run.
///
/// <para><b>Reproducibility is the point.</b> The same <c>.tmx</c> must produce
/// byte-identical JSON on every machine and every run, because a prefab that
/// varies breaks the guarantee that the world seed determines the world. So:
/// nothing is emitted in dictionary order (markers sort by y, then x, then type;
/// metadata keys sort with <see cref="StringComparer.Ordinal"/>), every number is
/// parsed and written invariantly, and the writer's newline is normalised to
/// <c>\n</c> because .NET 8's indented <c>Utf8JsonWriter</c> uses
/// <c>Environment.NewLine</c>.</para>
///
/// <para><b>Every problem is fatal.</b> An unmapped GID, a flipped tile, a
/// missing layer, a non-CSV layer encoding, an unknown marker type, an
/// out-of-bounds marker or an unrecognised map property all throw
/// <see cref="TiledConversionException"/> naming the offending thing. None of
/// them can be defaulted or skipped without shipping a structure that differs
/// from what the author drew, which nothing downstream can detect.</para>
///
/// <para><b>Map contract.</b> Orthogonal, finite, CSV layer format (Tiled: Map ▸
/// Map Properties ▸ Tile Layer Format ▸ CSV). Base64/zlib/zstd layer data is
/// deliberately out of scope — supporting it would mean a second decode path
/// that no committed map exercises, and CSV is a one-checkbox change for the
/// author. Two tile layers named exactly <c>blocks</c> and <c>walls</c>, both
/// required and both the size of the map. One object layer named
/// <c>markers</c>, optional.</para>
///
/// <para><b>Map custom properties.</b> Tiled properties are flat, so the nested
/// parts of <see cref="PrefabConstraints"/> use flat explicit names. Required:
/// <c>prefab_id</c> (string), <c>category</c> (string). Optional, with the
/// defaults of <see cref="PrefabConstraints"/> / <see cref="PrefabSpacing"/>:
/// <c>weight</c> (float, default <c>1</c>), <c>constraint_allowed_biomes</c>
/// (string, comma-separated, default empty = any), <c>constraint_allowed_layers</c>
/// (string, comma-separated <see cref="LayerCategory"/> names, default empty =
/// any), <c>constraint_requires_ground</c> (bool, default false),
/// <c>constraint_requires_cavern</c> (bool, default false),
/// <c>constraint_min_spacing_same_category</c> (int, default 0),
/// <c>constraint_min_spacing_any_category</c> (int, default 0),
/// <c>constraint_clearance_above</c> (int, default 0). Any other map property is
/// an error, because the alternative is a typo'd constraint name silently taking
/// its default. The same contract is restated for authors in
/// <c>content/tiled/README.md</c>.</para>
/// </summary>
public static class TiledPrefabConverter
{
    /// <summary>
    /// Tiled ORs these bits into a GID for horizontal / vertical / diagonal flip
    /// and hexagonal 120° rotation. The runtime prefab format has no flipped
    /// tile, so masking them off would ship a structure that does not match the
    /// map; any of them set is a fatal error instead.
    /// </summary>
    private const uint TransformBits = 0xF0000000u;

    /// <summary>The tile id left once <see cref="TransformBits"/> are excluded.</summary>
    private const uint GidMask = 0x0FFFFFFFu;

    /// <summary>Tile layer names the converter requires, in output order.</summary>
    private const string BlocksLayer = "blocks";
    private const string WallsLayer = "walls";

    /// <summary>Object layer holding markers. Optional: a decorative prefab has none.</summary>
    private const string MarkersLayer = "markers";

    /// <summary>
    /// Marker type strings accepted in a Tiled object's class, keyed by the same
    /// snake_case spelling the runtime JSON uses. Built from the enum so adding a
    /// <see cref="PrefabMarkerType"/> member needs no converter change.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, string> MarkerTypes = BuildSnakeNames<PrefabMarkerType>();

    /// <summary>Accepted <c>constraint_allowed_layers</c> entries, same construction as <see cref="MarkerTypes"/>.</summary>
    private static readonly IReadOnlyDictionary<string, string> LayerNames = BuildSnakeNames<LayerCategory>();

    /// <summary>
    /// Converts one map file, resolving any external <c>.tsx</c> relative to the
    /// <c>.tmx</c>'s own directory (which is how Tiled writes the reference).
    /// </summary>
    /// <exception cref="TiledConversionException">On any conversion problem, including an unreadable file.</exception>
    public static string ConvertFile(string tmxPath, TilesetMap tilesets)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tmxPath);
        ArgumentNullException.ThrowIfNull(tilesets);

        string name = Path.GetFileName(tmxPath);
        string directory = Path.GetDirectoryName(Path.GetFullPath(tmxPath)) ?? ".";

        return Convert(
            ReadText(tmxPath, name),
            name,
            tilesets,
            source => ReadText(Path.Combine(directory, source.Replace('\\', '/')), source));
    }

    /// <summary>
    /// The output file name for a map: <c>ruin_stone_small.tmx</c> becomes
    /// <c>ruin_stone_small.json</c>. One place, so the tool and the staleness test
    /// cannot disagree about which generated file belongs to which map.
    /// </summary>
    public static string OutputFileName(string tmxPath) =>
        Path.GetFileNameWithoutExtension(tmxPath) + ".json";

    /// <summary>
    /// Converts map XML held in memory. The seam the tests use: fixtures are
    /// inline strings, so a loud-failure test needs no committed broken map.
    /// </summary>
    /// <param name="sourceName">File name for error messages and the generated header.</param>
    /// <param name="readExternalTileset">
    /// Resolves a <c>&lt;tileset source="x.tsx"&gt;</c> reference to that file's
    /// XML. Only called for external tilesets, so a fixture with an embedded
    /// tileset may pass a delegate that throws.
    /// </param>
    /// <returns>
    /// The complete generated document, ending in a newline, with a leading
    /// <c>//</c> provenance header. The header is legal because
    /// <see cref="RegistryLoader.Options"/> skips comments.
    /// </returns>
    /// <exception cref="TiledConversionException">On any conversion problem.</exception>
    public static string Convert(
        string tmxXml,
        string sourceName,
        TilesetMap tilesets,
        Func<string, string> readExternalTileset)
    {
        ArgumentNullException.ThrowIfNull(tmxXml);
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceName);
        ArgumentNullException.ThrowIfNull(tilesets);
        ArgumentNullException.ThrowIfNull(readExternalTileset);

        XElement map = ParseMap(tmxXml, sourceName);

        int width = RequirePositiveInt(map, "width", sourceName);
        int height = RequirePositiveInt(map, "height", sourceName);
        int tileWidth = RequirePositiveInt(map, "tilewidth", sourceName);
        int tileHeight = RequirePositiveInt(map, "tileheight", sourceName);

        CheckMapKind(map, sourceName);

        List<TilesetRef> tilesetRefs = ReadTilesetRefs(map, sourceName, readExternalTileset);

        ushort[] blockIds = ReadTileLayer(
            map, BlocksLayer, width, height, sourceName, tilesetRefs,
            (TilesetMap m, string set, int local, out ushort id) => m.TryGetBlockId(set, local, out id),
            "block_id", tilesets);

        ushort[] wallIds = ReadTileLayer(
            map, WallsLayer, width, height, sourceName, tilesetRefs,
            (TilesetMap m, string set, int local, out ushort id) => m.TryGetWallId(set, local, out id),
            "wall_id", tilesets);

        List<Marker> markers = ReadMarkers(map, sourceName, width, height, tileWidth, tileHeight);
        PrefabProperties properties = ReadMapProperties(map, sourceName);

        return Write(sourceName, width, height, blockIds, wallIds, markers, properties);
    }

    // --- input ---------------------------------------------------------------

    /// <summary>Reads a file, turning IO failure into the converter's own fatal error.</summary>
    private static string ReadText(string path, string name)
    {
        try
        {
            return File.ReadAllText(path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new TiledConversionException(name, $"Could not be read: {ex.Message}", ex);
        }
    }

    /// <summary>Parses the document and returns its <c>&lt;map&gt;</c> root.</summary>
    private static XElement ParseMap(string xml, string sourceName)
    {
        XDocument document;
        try
        {
            document = XDocument.Parse(xml, LoadOptions.None);
        }
        catch (XmlException ex)
        {
            throw new TiledConversionException(sourceName, $"Malformed XML: {ex.Message}", ex);
        }

        XElement? root = document.Root;
        if (root is null || root.Name.LocalName != "map")
        {
            throw new TiledConversionException(
                sourceName, "Root element must be <map>; this does not look like a Tiled .tmx.");
        }

        return root;
    }

    /// <summary>
    /// Rejects map kinds the tile-array format cannot represent. An infinite map
    /// stores its data in chunks with no fixed origin, so it has no rectangle to
    /// convert; a non-orthogonal map's tile coordinates are not the prefab's grid.
    /// </summary>
    private static void CheckMapKind(XElement map, string sourceName)
    {
        string orientation = (string?)map.Attribute("orientation") ?? "orthogonal";
        if (!string.Equals(orientation, "orthogonal", StringComparison.Ordinal))
        {
            throw new TiledConversionException(
                sourceName,
                $"Map orientation is '{orientation}'; prefabs are a plain tile rectangle, " +
                "so the map must be orthogonal.");
        }

        if ((string?)map.Attribute("infinite") == "1")
        {
            throw new TiledConversionException(
                sourceName,
                "Map is infinite; a prefab is a fixed rectangle. Set Map ▸ Map Properties ▸ " +
                "Infinite off and resize the map to the prefab footprint.");
        }
    }

    // --- tilesets ------------------------------------------------------------

    /// <summary>A tileset attached to the map: its name, and the GID its local id 0 occupies.</summary>
    private readonly record struct TilesetRef(uint FirstGid, string Name);

    /// <summary>
    /// Reads every <c>&lt;tileset&gt;</c>, embedded or external, sorted by
    /// descending <c>firstgid</c> so resolving a GID is a first-match scan.
    /// </summary>
    private static List<TilesetRef> ReadTilesetRefs(
        XElement map, string sourceName, Func<string, string> readExternalTileset)
    {
        List<TilesetRef> refs = new();

        foreach (XElement element in map.Elements("tileset"))
        {
            uint firstGid = (uint)RequirePositiveInt(element, "firstgid", sourceName);
            string? source = (string?)element.Attribute("source");

            string name;
            if (source is null)
            {
                name = RequireAttribute(element, "name", sourceName);
            }
            else
            {
                // External .tsx: the name lives in the referenced file, not on the
                // reference, so the mapping keys off the same string either way.
                XDocument tsx;
                try
                {
                    tsx = XDocument.Parse(readExternalTileset(source));
                }
                catch (XmlException ex)
                {
                    throw new TiledConversionException(
                        sourceName, $"Tileset '{source}' is malformed XML: {ex.Message}", ex);
                }

                XElement? root = tsx.Root;
                if (root is null || root.Name.LocalName != "tileset")
                {
                    throw new TiledConversionException(
                        sourceName, $"Tileset '{source}' has no <tileset> root element.");
                }

                name = RequireAttribute(root, "name", sourceName);
            }

            refs.Add(new TilesetRef(firstGid, name));
        }

        if (refs.Count == 0)
        {
            throw new TiledConversionException(sourceName, "Map has no <tileset>.");
        }

        refs.Sort(static (a, b) => b.FirstGid.CompareTo(a.FirstGid));
        return refs;
    }

    /// <summary>
    /// Resolves a raw GID to its tileset and local id. Assumes the transform bits
    /// have already been rejected — call <see cref="CheckTransformBits"/> first,
    /// or the returned local id is nonsense.
    /// </summary>
    private static TilesetRef ResolveTileset(
        List<TilesetRef> refs, uint gid, string sourceName, string layer, int x, int y)
    {
        foreach (TilesetRef candidate in refs)
        {
            if (gid >= candidate.FirstGid)
            {
                return candidate;
            }
        }

        throw new TiledConversionException(
            sourceName,
            $"Layer '{layer}' tile ({x},{y}) has gid {gid}, which is below every tileset's firstgid.");
    }

    // --- tile layers ---------------------------------------------------------

    /// <summary>Numeric-id probe for one of the two tile registries; see <see cref="TilesetMap"/>.</summary>
    private delegate bool TileIdLookup(TilesetMap map, string tileset, int localId, out ushort id);

    /// <summary>
    /// Reads one required CSV tile layer into a row-major <c>width * height</c>
    /// array, using this prefab's own width as the stride (never the chunk's 64).
    /// </summary>
    private static ushort[] ReadTileLayer(
        XElement map,
        string layerName,
        int width,
        int height,
        string sourceName,
        List<TilesetRef> tilesetRefs,
        TileIdLookup lookup,
        string idField,
        TilesetMap tilesets)
    {
        XElement layer = map.Elements("layer")
            .FirstOrDefault(e => (string?)e.Attribute("name") == layerName)
            ?? throw new TiledConversionException(
                sourceName,
                $"No tile layer named '{layerName}'. A prefab needs both '{BlocksLayer}' and " +
                $"'{WallsLayer}' tile layers, spelled exactly.");

        if (RequirePositiveInt(layer, "width", sourceName) != width
            || RequirePositiveInt(layer, "height", sourceName) != height)
        {
            throw new TiledConversionException(
                sourceName,
                $"Layer '{layerName}' is {(string?)layer.Attribute("width")}x" +
                $"{(string?)layer.Attribute("height")}, but the map is {width}x{height}.");
        }

        XElement data = layer.Element("data")
            ?? throw new TiledConversionException(sourceName, $"Layer '{layerName}' has no <data>.");

        string encoding = (string?)data.Attribute("encoding") ?? "xml";
        if (!string.Equals(encoding, "csv", StringComparison.Ordinal)
            || data.Attribute("compression") is not null)
        {
            throw new TiledConversionException(
                sourceName,
                $"Layer '{layerName}' uses '{encoding}' encoding" +
                (data.Attribute("compression") is null ? "" : " with compression") +
                ". Set Map ▸ Map Properties ▸ Tile Layer Format to CSV and re-save; " +
                "base64 and compressed layer data are not supported.");
        }

        ushort[] ids = new ushort[width * height];
        int index = 0;

        foreach (string token in data.Value.Split(',', StringSplitOptions.TrimEntries))
        {
            if (token.Length == 0)
            {
                continue;
            }

            if (index >= ids.Length)
            {
                throw new TiledConversionException(
                    sourceName,
                    $"Layer '{layerName}' holds more than {ids.Length} tiles for a " +
                    $"{width}x{height} map.");
            }

            if (!uint.TryParse(token, NumberStyles.Integer, CultureInfo.InvariantCulture, out uint gid))
            {
                throw new TiledConversionException(
                    sourceName, $"Layer '{layerName}' has non-numeric CSV entry '{token}'.");
            }

            int x = index % width;
            int y = index / width;
            ids[index] = ResolveTile(gid, sourceName, layerName, x, y, tilesetRefs, lookup, idField, tilesets);
            index++;
        }

        if (index != ids.Length)
        {
            throw new TiledConversionException(
                sourceName,
                $"Layer '{layerName}' holds {index} tiles, but the map is {width}x{height} " +
                $"and needs exactly {ids.Length}.");
        }

        return ids;
    }

    /// <summary>
    /// One GID to one numeric id. GID 0 is Tiled's empty tile and maps to id 0
    /// (air / no wall) with no mapping entry, which is why <c>tileset_map.json</c>
    /// never has to spell out emptiness.
    /// </summary>
    private static ushort ResolveTile(
        uint gid,
        string sourceName,
        string layerName,
        int x,
        int y,
        List<TilesetRef> tilesetRefs,
        TileIdLookup lookup,
        string idField,
        TilesetMap tilesets)
    {
        CheckTransformBits(gid, sourceName, layerName, x, y);

        if (gid == 0)
        {
            return 0;
        }

        TilesetRef tileset = ResolveTileset(tilesetRefs, gid, sourceName, layerName, x, y);
        int localId = (int)(gid - tileset.FirstGid);

        if (!lookup(tilesets, tileset.Name, localId, out ushort id))
        {
            throw new TiledConversionException(
                sourceName,
                $"Layer '{layerName}' tile ({x},{y}) uses tileset '{tileset.Name}' local id " +
                $"{localId} (gid {gid}), which has no '{idField}' in tileset_map.json" +
                (tilesets.HasTileset(tileset.Name)
                    ? "."
                    : $"; that tileset is not in the mapping at all."));
        }

        return id;
    }

    /// <summary>
    /// Rejects a flipped or rotated tile. Masking the bits off would convert
    /// cleanly and produce a structure mirrored away from what the author drew,
    /// with nothing downstream able to notice.
    /// </summary>
    private static void CheckTransformBits(uint gid, string sourceName, string layerName, int x, int y)
    {
        if ((gid & TransformBits) == 0)
        {
            return;
        }

        throw new TiledConversionException(
            sourceName,
            $"Layer '{layerName}' tile ({x},{y}) is flipped or rotated (gid 0x{gid:X8}, " +
            $"tile id {gid & GidMask}). The prefab format has no flipped tile, so draw the " +
            "tile unflipped or add a pre-flipped tile to the tileset.");
    }

    // --- markers -------------------------------------------------------------

    /// <summary>One converted marker, held until the whole set can be sorted.</summary>
    private sealed record Marker(string Type, int X, int Y, List<KeyValuePair<string, TiledProperty>> Metadata);

    /// <summary>
    /// Reads the optional <c>markers</c> object layer, converting pixel positions
    /// to tile-local coordinates and sorting the result by y, then x, then type
    /// so the generated file cannot move when Tiled reorders its objects.
    /// </summary>
    private static List<Marker> ReadMarkers(
        XElement map, string sourceName, int width, int height, int tileWidth, int tileHeight)
    {
        List<Marker> markers = new();

        XElement? layer = map.Elements("objectgroup")
            .FirstOrDefault(e => (string?)e.Attribute("name") == MarkersLayer);

        if (layer is null)
        {
            return markers;
        }

        foreach (XElement obj in layer.Elements("object"))
        {
            // Tiled 1.9 renamed an object's "type" attribute to "class"; both
            // spellings are in the wild, and a map saved by either version must
            // convert the same way.
            string? className = (string?)obj.Attribute("class") ?? (string?)obj.Attribute("type");

            if (string.IsNullOrWhiteSpace(className))
            {
                throw new TiledConversionException(
                    sourceName,
                    $"Marker object id {(string?)obj.Attribute("id") ?? "?"} has no class; " +
                    "set the object's Class to a marker type " +
                    $"({string.Join(", ", MarkerTypes.Keys.Order(StringComparer.Ordinal))}).");
            }

            if (!MarkerTypes.TryGetValue(className, out string? markerType))
            {
                throw new TiledConversionException(
                    sourceName,
                    $"Marker object class '{className}' is not a marker type. Valid types: " +
                    $"{string.Join(", ", MarkerTypes.Keys.Order(StringComparer.Ordinal))}.");
            }

            // Tiled stores object positions in pixels; the prefab grid is tiles.
            // Floor rather than round, so an object nudged a pixel past a tile's
            // centre still belongs to the tile it visibly sits in.
            double px = RequireDouble(obj, "x", sourceName);
            double py = RequireDouble(obj, "y", sourceName);
            int x = (int)Math.Floor(px / tileWidth);
            int y = (int)Math.Floor(py / tileHeight);

            if ((uint)x >= (uint)width || (uint)y >= (uint)height)
            {
                throw new TiledConversionException(
                    sourceName,
                    $"Marker '{markerType}' at pixel ({px.ToString(CultureInfo.InvariantCulture)}," +
                    $"{py.ToString(CultureInfo.InvariantCulture)}) is tile ({x},{y}), outside the " +
                    $"map's x [0,{width}) y [0,{height}).");
            }

            markers.Add(new Marker(markerType, x, y, ReadProperties(obj, sourceName, $"marker '{markerType}'")));
        }

        markers.Sort(static (a, b) =>
        {
            int order = a.Y.CompareTo(b.Y);
            if (order != 0)
            {
                return order;
            }

            order = a.X.CompareTo(b.X);
            return order != 0 ? order : string.CompareOrdinal(a.Type, b.Type);
        });

        return markers;
    }

    // --- properties ----------------------------------------------------------

    /// <summary>A Tiled custom property: its declared type and its raw string value.</summary>
    private readonly record struct TiledProperty(string Type, string Value);

    /// <summary>
    /// Reads a <c>&lt;properties&gt;</c> block into key order (ordinal), so a
    /// marker's metadata is emitted the same way whatever order Tiled saved it in.
    /// </summary>
    /// <param name="owner">Where the property came from, for error messages.</param>
    private static List<KeyValuePair<string, TiledProperty>> ReadProperties(
        XElement element, string sourceName, string owner)
    {
        List<KeyValuePair<string, TiledProperty>> properties = new();
        XElement? block = element.Element("properties");

        if (block is null)
        {
            return properties;
        }

        foreach (XElement property in block.Elements("property"))
        {
            string name = RequireAttribute(property, "name", sourceName);
            string type = (string?)property.Attribute("type") ?? "string";

            // Tiled writes multi-line string values as element text rather than
            // an attribute, so both places have to be read.
            string value = (string?)property.Attribute("value") ?? property.Value;

            if (type is not ("string" or "int" or "float" or "bool"))
            {
                throw new TiledConversionException(
                    sourceName,
                    $"Property '{name}' on {owner} has type '{type}'; only string, int, float " +
                    "and bool survive the conversion to prefab JSON.");
            }

            if (properties.Any(p => string.Equals(p.Key, name, StringComparison.Ordinal)))
            {
                throw new TiledConversionException(
                    sourceName, $"Property '{name}' on {owner} is declared twice.");
            }

            properties.Add(new KeyValuePair<string, TiledProperty>(name, new TiledProperty(type, value)));
        }

        properties.Sort(static (a, b) => string.CompareOrdinal(a.Key, b.Key));
        return properties;
    }

    /// <summary>The prefab-level fields that come from map custom properties.</summary>
    private sealed record PrefabProperties(
        string PrefabId,
        string Category,
        float Weight,
        IReadOnlyList<string> AllowedBiomes,
        IReadOnlyList<string> AllowedLayers,
        bool RequiresGround,
        bool RequiresCavern,
        int SameCategorySpacing,
        int AnyCategorySpacing,
        int ClearanceAbove);

    /// <summary>
    /// Reads the flat map-property contract documented on this type. Consumes
    /// known names and then rejects whatever is left, so a misspelled constraint
    /// is a failure rather than a constraint silently taking its default.
    /// </summary>
    private static PrefabProperties ReadMapProperties(XElement map, string sourceName)
    {
        Dictionary<string, TiledProperty> properties = new(StringComparer.Ordinal);
        foreach (KeyValuePair<string, TiledProperty> entry in ReadProperties(map, sourceName, "the map"))
        {
            properties[entry.Key] = entry.Value;
        }

        PrefabProperties result = new(
            PrefabId: TakeString(properties, "prefab_id", sourceName, required: true),
            Category: TakeString(properties, "category", sourceName, required: true),
            Weight: TakeFloat(properties, "weight", sourceName, 1f),
            AllowedBiomes: SplitList(TakeString(properties, "constraint_allowed_biomes", sourceName, required: false)),
            AllowedLayers: TakeLayers(properties, sourceName),
            RequiresGround: TakeBool(properties, "constraint_requires_ground", sourceName),
            RequiresCavern: TakeBool(properties, "constraint_requires_cavern", sourceName),
            SameCategorySpacing: TakeInt(properties, "constraint_min_spacing_same_category", sourceName),
            AnyCategorySpacing: TakeInt(properties, "constraint_min_spacing_any_category", sourceName),
            ClearanceAbove: TakeInt(properties, "constraint_clearance_above", sourceName));

        if (properties.Count > 0)
        {
            throw new TiledConversionException(
                sourceName,
                $"Unrecognised map properties: {string.Join(", ", properties.Keys.Order(StringComparer.Ordinal))}. " +
                "Check the spelling against the contract in content/tiled/README.md; an unknown " +
                "property is refused rather than ignored, because a typo would otherwise leave " +
                "the constraint at its default.");
        }

        return result;
    }

    /// <summary>Consumes a string property. Required ones may not be blank.</summary>
    private static string TakeString(
        Dictionary<string, TiledProperty> properties, string name, string sourceName, bool required)
    {
        if (!properties.Remove(name, out TiledProperty property))
        {
            if (required)
            {
                throw new TiledConversionException(
                    sourceName, $"Map property '{name}' is required and missing.");
            }

            return string.Empty;
        }

        RequirePropertyType(property, name, sourceName, "string");

        if (required && string.IsNullOrWhiteSpace(property.Value))
        {
            throw new TiledConversionException(sourceName, $"Map property '{name}' is empty.");
        }

        return property.Value;
    }

    /// <summary>Consumes an optional int property; absent means 0, matching <see cref="PrefabConstraints"/>.</summary>
    private static int TakeInt(Dictionary<string, TiledProperty> properties, string name, string sourceName)
    {
        if (!properties.Remove(name, out TiledProperty property))
        {
            return 0;
        }

        RequirePropertyType(property, name, sourceName, "int");

        if (!int.TryParse(property.Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out int value))
        {
            throw new TiledConversionException(
                sourceName, $"Map property '{name}' value '{property.Value}' is not an integer.");
        }

        return value;
    }

    /// <summary>Consumes an optional float property. Tiled writes an unedited numeric property as int, so both types are accepted.</summary>
    private static float TakeFloat(
        Dictionary<string, TiledProperty> properties, string name, string sourceName, float fallback)
    {
        if (!properties.Remove(name, out TiledProperty property))
        {
            return fallback;
        }

        RequirePropertyType(property, name, sourceName, "float", "int");

        if (!float.TryParse(property.Value, NumberStyles.Float, CultureInfo.InvariantCulture, out float value))
        {
            throw new TiledConversionException(
                sourceName, $"Map property '{name}' value '{property.Value}' is not a number.");
        }

        return value;
    }

    /// <summary>Consumes an optional bool property; absent means false.</summary>
    private static bool TakeBool(Dictionary<string, TiledProperty> properties, string name, string sourceName)
    {
        if (!properties.Remove(name, out TiledProperty property))
        {
            return false;
        }

        RequirePropertyType(property, name, sourceName, "bool");

        return property.Value switch
        {
            "true" or "1" => true,
            "false" or "0" => false,
            _ => throw new TiledConversionException(
                sourceName, $"Map property '{name}' value '{property.Value}' is not a bool."),
        };
    }

    /// <summary>
    /// Consumes <c>constraint_allowed_layers</c> and proves every entry names a
    /// <see cref="LayerCategory"/>. A misspelled layer would otherwise parse as
    /// valid JSON and place the prefab nowhere.
    /// </summary>
    private static IReadOnlyList<string> TakeLayers(
        Dictionary<string, TiledProperty> properties, string sourceName)
    {
        IReadOnlyList<string> raw = SplitList(
            TakeString(properties, "constraint_allowed_layers", sourceName, required: false));

        foreach (string layer in raw)
        {
            if (!LayerNames.ContainsKey(layer))
            {
                throw new TiledConversionException(
                    sourceName,
                    $"Map property 'constraint_allowed_layers' names '{layer}', which is not a " +
                    $"world layer. Valid: {string.Join(", ", LayerNames.Keys.Order(StringComparer.Ordinal))}.");
            }
        }

        return raw;
    }

    /// <summary>Enforces a property's declared Tiled type, so a value is never reinterpreted.</summary>
    private static void RequirePropertyType(
        TiledProperty property, string name, string sourceName, params string[] accepted)
    {
        if (!accepted.Contains(property.Type, StringComparer.Ordinal))
        {
            throw new TiledConversionException(
                sourceName,
                $"Map property '{name}' is declared as '{property.Type}' in Tiled; " +
                $"it must be {string.Join(" or ", accepted)}.");
        }
    }

    /// <summary>
    /// Splits a comma-separated list property. Order is the author's, because an
    /// allow-list is only ever tested for membership; blanks are dropped so a
    /// trailing comma is not an empty biome id.
    /// </summary>
    private static IReadOnlyList<string> SplitList(string value) =>
        value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

    // --- output --------------------------------------------------------------

    /// <summary>
    /// Serialises the converted prefab. Property order is written by hand rather
    /// than reflected, and indentation, newline and number formatting are all
    /// fixed, so the bytes depend only on the map — see the determinism note on
    /// this type.
    /// </summary>
    private static string Write(
        string sourceName,
        int width,
        int height,
        ushort[] blockIds,
        ushort[] wallIds,
        List<Marker> markers,
        PrefabProperties properties)
    {
        using MemoryStream stream = new();
        using (Utf8JsonWriter writer = new(stream, new JsonWriterOptions { Indented = true }))
        {
            writer.WriteStartObject();
            writer.WriteString("prefab_id", properties.PrefabId);
            writer.WriteString("category", properties.Category);

            writer.WriteStartObject("dimensions");
            writer.WriteNumber("width", width);
            writer.WriteNumber("height", height);
            writer.WriteEndObject();

            writer.WriteStartObject("constraints");
            WriteStringArray(writer, "allowed_biomes", properties.AllowedBiomes);
            WriteStringArray(writer, "allowed_layers", properties.AllowedLayers);
            writer.WriteBoolean("requires_ground", properties.RequiresGround);
            writer.WriteBoolean("requires_cavern", properties.RequiresCavern);
            writer.WriteStartObject("min_spacing");
            writer.WriteNumber("same_category", properties.SameCategorySpacing);
            writer.WriteNumber("any_category", properties.AnyCategorySpacing);
            writer.WriteEndObject();
            writer.WriteNumber("clearance_above", properties.ClearanceAbove);
            writer.WriteEndObject();

            WriteTileArray(writer, "block_ids", blockIds);
            WriteTileArray(writer, "wall_ids", wallIds);

            writer.WriteStartArray("markers");
            foreach (Marker marker in markers)
            {
                writer.WriteStartObject();
                writer.WriteString("type", marker.Type);
                writer.WriteNumber("x", marker.X);
                writer.WriteNumber("y", marker.Y);
                writer.WriteStartObject("metadata");
                foreach (KeyValuePair<string, TiledProperty> entry in marker.Metadata)
                {
                    WriteTypedValue(writer, entry.Key, entry.Value);
                }

                writer.WriteEndObject();
                writer.WriteEndObject();
            }

            writer.WriteEndArray();

            // float, not double: PrefabDefinition.Weight is a float, and writing
            // the double widening would print 0.25 as 0.25 but 0.1 as
            // 0.10000000149011612.
            writer.WriteNumber("weight", properties.Weight);
            writer.WriteEndObject();
        }

        string json = Encoding.UTF8.GetString(stream.ToArray());

        // .NET 8's indented writer emits Environment.NewLine, which would make the
        // committed file differ between Windows and Linux and fail the staleness
        // test on whichever machine did not generate it.
        json = json.Replace("\r\n", "\n", StringComparison.Ordinal);

        return Header(sourceName) + json + "\n";
    }

    /// <summary>
    /// Provenance header. A <c>//</c> comment rather than a JSON field because
    /// <see cref="RegistryLoader.Options"/> skips comments, so this stays out of
    /// <see cref="PrefabDefinition"/>'s schema entirely.
    /// </summary>
    private static string Header(string sourceName) =>
        $"// GENERATED FILE - do not hand-edit.\n" +
        $"// Converted from content/tiled/{sourceName} by Void.Tools tmx-convert (VOID-026).\n" +
        $"// Edit the .tmx in Tiled and regenerate; a stale file fails Void.Tests.\n";

    private static void WriteStringArray(Utf8JsonWriter writer, string name, IReadOnlyList<string> values)
    {
        writer.WriteStartArray(name);
        foreach (string value in values)
        {
            writer.WriteStringValue(value);
        }

        writer.WriteEndArray();
    }

    private static void WriteTileArray(Utf8JsonWriter writer, string name, ushort[] ids)
    {
        writer.WriteStartArray(name);
        foreach (ushort id in ids)
        {
            writer.WriteNumberValue(id);
        }

        writer.WriteEndArray();
    }

    /// <summary>
    /// Emits one metadata entry in the JSON type Tiled declared for it, so a
    /// numeric loot tier stays a number and does not arrive at the placement
    /// engine as a string.
    /// </summary>
    private static void WriteTypedValue(Utf8JsonWriter writer, string name, TiledProperty property)
    {
        switch (property.Type)
        {
            case "int":
                writer.WriteNumber(name, ParseIntValue(name, property.Value));
                break;

            case "float":
                writer.WriteNumber(name, ParseFloatValue(name, property.Value));
                break;

            case "bool":
                writer.WriteBoolean(name, property.Value is "true" or "1");
                break;

            default:
                writer.WriteString(name, property.Value);
                break;
        }
    }

    private static int ParseIntValue(string name, string value) =>
        int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out int parsed)
            ? parsed
            : throw new TiledConversionException($"Property '{name}' value '{value}' is not an integer.");

    private static float ParseFloatValue(string name, string value) =>
        float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed)
            ? parsed
            : throw new TiledConversionException($"Property '{name}' value '{value}' is not a number.");

    // --- small shared helpers ------------------------------------------------

    /// <summary>Snake_case spelling of every member of an enum, matching how <see cref="RegistryLoader.Options"/> serialises it.</summary>
    private static IReadOnlyDictionary<string, string> BuildSnakeNames<TEnum>()
        where TEnum : struct, Enum
    {
        Dictionary<string, string> names = new(StringComparer.Ordinal);
        foreach (string name in Enum.GetNames<TEnum>())
        {
            string snake = JsonNamingPolicy.SnakeCaseLower.ConvertName(name);
            names[snake] = snake;
        }

        return names;
    }

    private static string RequireAttribute(XElement element, string name, string sourceName) =>
        (string?)element.Attribute(name)
        ?? throw new TiledConversionException(
            sourceName, $"<{element.Name.LocalName}> has no '{name}' attribute.");

    /// <summary>Reads an attribute that must be a positive integer — every size and firstgid is one.</summary>
    private static int RequirePositiveInt(XElement element, string name, string sourceName)
    {
        string raw = RequireAttribute(element, name, sourceName);

        if (!int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out int value) || value <= 0)
        {
            throw new TiledConversionException(
                sourceName,
                $"<{element.Name.LocalName}> attribute '{name}' is '{raw}'; expected a positive integer.");
        }

        return value;
    }

    /// <summary>Reads an attribute that must be a number — object pixel positions, which Tiled may write fractionally.</summary>
    private static double RequireDouble(XElement element, string name, string sourceName)
    {
        string raw = RequireAttribute(element, name, sourceName);

        if (!double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out double value))
        {
            throw new TiledConversionException(
                sourceName,
                $"<{element.Name.LocalName}> attribute '{name}' is '{raw}'; expected a number.");
        }

        return value;
    }
}
